Add staging metadata for matterverse.ai
Materials-Consortia/providers pull request #83
Opened 2022-09-12 16:31 UTC by ml-evs

Add placeholder for https://matterverse.ai, an in progress OPTIMADE API.

@JiQi535 @christen03

2022-09-23 07:55 UTC, merkys commented on src/index-metadbs/matterverse/v1/links.json
> +            "description": "Database of 31 million hypothetical materials generated through advanced machine learning algorithms",
I personally would not add the number ("31 million") as it may change in the future and may become out-of-sync. Maybe change to "over 31 million"?

2022-09-30 15:13 UTC, christen03 requested changes

2022-09-30 15:16 UTC, merkys commented on src/index-metadbs/matterverse/v1/links.json
> +            "base_url": "https://providers.optimade.org",
`base_url` has to be an URL, thus either `http://` or `https://` will be needed.

2022-09-30 15:23 UTC, ml-evs commented on src/index-metadbs/matterverse/v1/links.json
> +            "base_url": "https://providers.optimade.org",
This is also not the `base_url` that you want to change, this is mean to be an additional link back to the providers list. The one you want to change is currently `null` (I'll tag you in a comment at the correct line)

2022-09-30 15:23 UTC, ml-evs commented on src/index-metadbs/matterverse/v1/links.json
> +            "base_url": null,
@christen03 this is the one!

2024-06-10 07:04 UTC, ml-evs commented
Superseded by #101

2024-06-10 07:04 UTC, closed without merging